### ISSUE TITLE
Unable to load dynamic library 'imagick'

### ISSUE THREAD

**Issue by hyoa** [stechstudio/bref-extensions#1] opened 2019-03-04 14:25 UTC
Hello

I have tried to use your work to have imagick available into a function created with Bref but I encounter some issue.

First, `make extensions` cannot work. -v flag doesn't exist on `docker build` command. I have tried to update the `Dockerfile` by doing a copy, but where does the `/artifacts` directory come from ?

Second, I have update the `make extensions` command to be able to pusblish the layer. But once the layer publish and attached to the function, I am not able to load `Imagick`.

I have created a `php/conf.d/php.ini` like mentionned in the Bref documentation  with `extension=imagick` or `extension=imagick.so` but nothing seems to be working. I have the following error when launching the function:
`
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: /opt/bref/lib/php/extensions/no-debug-zts-20180731/imagick (/opt/bref/lib/php/extensions/no-debug-zts-20180731/imagick: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-zts-20180731/imagick.so (/opt/bref/lib/php/extensions/no-debug-zts-20180731/imagick.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

I have launch the docker image create by `make extensions` and  I have the same result than in the Readme.md.

I am wondering what am I doing wrong ? 

Thanks for your help !

**Comment by bubba-h57** [comment] 2019-03-04 14:33
If you simply want the output of the repo, as is ... you can head over to https://github.com/stechstudio/bref-extensions/releases and download the v1.0.0 [sts-bref-extension-7.3-layer.zip](https://github.com/stechstudio/bref-extensions/releases/download/v1.0.0/sts-bref-extension-7.3-layer.zip) then no need to build anything.

I will need to take a longer look at the issue report after work to better address the issue.

**Comment by bubba-h57** [comment] 2019-03-05 17:19
@hyoa There was definitely a bug in there. I took care of it though. You should be able to:

```
$ cd bref-extensions
$ git pull
$ git submodule pull
$ make
```
and let me know if that works for you now? I'll wait to hear from you prior to closing the issue.

**Comment by hyoa** [comment] 2019-03-05 20:12
Its working fine
`make` now run without exception and I have Imagick running in my lambda

Something to note is that, in your Bref application, when adding a configuration you have to give the full path for the location of the extension: `extension=/opt/sts/modules/imagick.so` (It took me some time to understand that...)

Thanks for your help, much appreciated !

**Comment by Sh1d0w** [comment] 2019-03-28 06:29
@hyoa How did you resolve this issue? I've downloaded the release zip from this repo, created new layer in AWS with it. Added the layer to my template file

```
Layers:
                - 'arn:aws:lambda:eu-central-1:209497400698:layer:php-73-fpm:3'
                - 'arn:aws:lambda:eu-central-1:843597560967:layer:sts-bref-extensions:1'
```

Also added `extension=/opt/sts/modules/imagick.so` to my `php/conf.d/php.ini` but I get

`PHP Startup: Unable to load dynamic library '/opt/sts/modules/imagick.so'`

when I run my lamda function?

**Comment by hyoa** [comment] 2019-03-28 07:23
In `php.ini` right ? No `php.init` ?

I didn't try with the zip in the release as I rebuild the layer using the `Makefile`

**Comment by Sh1d0w** [comment] 2019-03-28 07:25
@hyoa yes, `php.ini` that was a typo here. I guess I will have to rebuild it as well. @bubba-h57 can you please check or advise regarding the release zip?

**Comment by bubba-h57** [comment] 2019-04-12 12:28
I will check it out today and get back to you @Sh1d0w

**Comment by bubba-h57** [comment] 2019-04-12 13:23
@Sh1d0w I am currently using:

```php
BREF_FUNCTION_LAYER_1=arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:2
BREF_FUNCTION_LAYER_2=arn:aws:lambda:us-east-1:965741605173:layer:sts-bref-extensions:2
```

Running the following:

```php
       LambdaRoute::register(
            Event::class,
            function (Event $event, Context $context): array {
                $loaded = get_loaded_extensions();
                sort($loaded);
                Log::debug(sprintf('Loaded Modules: %s', implode(', ', $loaded)));
                Log::debug(sprintf('The Default Log Driver: %s', Log::getDefaultDriver()));
                Log::debug(sprintf('Available Executables in /opt/bin/: %s', implode(', ', File::files('/opt/bin'))));
                Log::debug(sprintf('The Event Type Is: %s', get_class($event)));
                return ['status' => 'success'];
            }
        );
```

I find in the logs:
```text
2019-04-12T13:12:12+0000 priority=DEBUG, transactionID="5cb08eac1d5ed", environment="test", httpHost="CLI", message="Loaded Modules: Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gettext, hash, iconv, imagick, json, libxml, mbstring, mysqlnd, openssl, pcntl, pcre, pdo_sqlite, posix, pthreads, readline, session, sodium, sqlite3, standard, tokenizer, vips, xml, xmlreader, xmlwriter, zip, zlib"
```

So I am getting the *imagick* module loaded with no problem. As for registering the libraries with PHP, I generating the following structure in my Function Package:

```text
/var/task/php/conf.d/imagick.ini
/var/task/php/conf.d/vips.ini
```

imagick.ini
```ini
extension = /opt/sts/modules/imagick.so
```

vips.ini
```ini
extension = /opt/sts/modules/vips.so
```

How about giving `arn:aws:lambda:us-east-1:965741605173:layer:sts-bref-extensions:2` a try directly and see if that "just works". Then, if you really need to roll your own layer, I can provide some more instruction on how to do that?

**Comment by Sh1d0w** [comment] 2019-04-12 13:40
@bubba-h57 Thanks for looking into this. Unfortunately I still get the same error. I even can not get to hit the PHP code, because FPM fails before that.

I have added your layer in my Lamda function:

<img width="1533" alt="Screenshot 2019-04-12 at 16 38 55" src="https://user-images.githubusercontent.com/5074917/56041520-9c6a9980-5d41-11e9-9479-54a5c5745c1c.png">

I have added `extension=/opt/sts/modules/imagick.so` to my php.ini

But the request timeouts and in CloudWatch logs I have this:

<img width="1447" alt="Screenshot 2019-04-12 at 16 39 04" src="https://user-images.githubusercontent.com/5074917/56041568-b310f080-5d41-11e9-911b-fc5f35fbf789.png">

Not sure if I am doing something wrong ...

**Comment by bubba-h57** [comment] 2019-04-12 13:42
The second layer in the screenshot does not appear to be our layer? Looks like it is the same one you used previously? Or maybe it is just the wrong screenshot?

**Comment by bubba-h57** [comment] 2019-04-12 13:45
Oh ... I also see you are using a more recent version (4) of the `arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm` layer where I am still using version two. I will be thoroughly surprised if that is a cause for concern, but it is worth noting the difference.

**Comment by Sh1d0w** [comment] 2019-04-12 13:52
@bubba-h57 This is the layer I've created from the zip file in the releases tab in this repository. It is just created in different region. From my understanding I had to create my own layer in my account with the zip file downloaded from here, since I can not include yours 

arn:aws:lambda:us-east-1:965741605173:layer:sts-bref-extensions:2

If I try it it gives me permission denied.

Yeah maybe the problem is in the most recent version of FPM layer, haven't tried with version 2, I've initially used version 3 where it also did not work.

**Comment by bubba-h57** [comment] 2019-04-12 13:59
Ok. Take a look at the instructions I provided at https://github.com/mnapoli/bref/issues/302#issuecomment-482147606

That will allow you to directly download the layer I am using and then upload it to your region. Skip the .zip file on github altogether.

**Comment by Sh1d0w** [comment] 2019-04-12 14:16
@bubba-h57 Thanks, but I don't have access to your layer, it seems like it is private

```
aws lambda get-layer-version --layer-name arn:aws:lambda:us-east-1:965741605173:layer:sts-bref-extensions --version-number 2
```

I get

```
An error occurred (AccessDeniedException) when calling the GetLayerVersion operation: User: arn:aws:iam::843597560967:user/my-user is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:965741605173:layer:sts-bref-extensions:2
```

Can you confirm this layer has public permission?

**Comment by bubba-h57** [comment] 2019-04-12 14:28
Sorry about that. I just made `GetLayerVersion` public for you.

```
aws lambda add-layer-version-permission --layer-name arn:aws:lambda:us-east-1:965741605173:layer:sts-bref-extensions --version-number 2 --statement-id public --action lambda:GetLayerVersion --output text --principal '*'
c905aa8b-89bd-4909-ac82-0e5741188703    {"Sid":"public","Effect":"Allow","Principal":"*","Action":"lambda:GetLayerVersion","Resource":"arn:aws:lambda:us-east-1:965741605173:layer:sts-bref-extensions:2"}
```

**Closed as completed** 2019-04-17 15:36 UTC
Labels: Type: Question
